fix: deduplicate Catalog
Stremio/stremio-core-web pull request #53
Opened 2023-06-30 09:52 UTC by elpiel

- [x] deduplicate Discovery board - removes any MetaItems that are found to more than 1 page, keeping the order of the elements
- [ ] deduplicate Catalogs with extra

2023-07-01 04:22 UTC, unclekingpin requested changes

2023-07-01 04:22 UTC, unclekingpin commented on src/model/serialize_catalogs_with_extra.rs
> +                                    .clone()
cloning the meta items just before take(10) looks like a bad idea
why is all of this cloning necessary ?
check #54

2023-07-04 07:40 UTC, elpiel commented on src/model/serialize_catalogs_with_extra.rs
> +                                    .clone()
It was when I was using the `Vec::dedup_by`, it's not necessary anymore.

2023-07-05 14:37 UTC, unclekingpin requested changes

2023-07-05 14:37 UTC, unclekingpin commented on src/model/serialize_discover.rs
> +                            .unique_by(|meta| meta.meta_item.id.clone())
why .clone is used here?
No cloning was needed in #54

2023-07-07 11:13 UTC, elpiel commented on src/model/serialize_discover.rs
> +                            .unique_by(|meta| meta.meta_item.id.clone())
Fixed.

2023-07-17 12:07 UTC, merged